#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
if env["target"] == "debug":
    env.Append(CPPDEFINES=["DEBUG_ENABLED", "DEBUG_METHODS_ENABLED"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "../../gd3dtopdown_godot/bin/libgd3dtopdown.{}.{}.{}{}".format(
        env["platform"], env["target"], env["arch_suffix"], env["SHLIBSUFFIX"]
    ),
    source=sources,
)

Default(library)
