#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])

#Allows the use of the {func}_handle 's in release mode
env.AppendUnique(CPPDEFINES=["TEST_FUNCTIONS"])


if env["target"] in ["editor", "template_debug"]:
    env.AppendUnique(CPPDEFINES=["DEBUG_ENABLED", "DEBUG_METHODS_ENABLED"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "../../gd3dtopdown_godot/bin/libgd3dtopdown{}{}".format(
         env["suffix"], env["SHLIBSUFFIX"]
    ),
    source=sources,
)

Default(library)
